# Generated by Django 3.0.4 on 2020-05-07 00:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200506_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=100, verbose_name='Nombre'),
        ),
    ]
